# Generated by Django 5.0.3 on 2024-03-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_myuser_profile_picture'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='FollowUser',
        ),
    ]
