# Generated by Django 5.0.3 on 2024-03-13 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_myuser_profile_picture'),
        ('blog', '0002_rename_follow_followuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuser',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='authentication.myuser'),
        ),
    ]
