# Generated by Django 5.0.3 on 2024-04-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_myuser_follower_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='follower_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
